config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :users , :path => 'login'
  root :to=> 'index#index'

 
  resources :autors, :path => 'Autores'
 
  resources :usuarios, :path => 'Usuarios'
  resources :books, :path => 'Libros'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/autor.rb
class Autor < ApplicationRecord
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: [:show, :edit, :update, :destroy]

  # GET /autors
  # GET /autors.json
  def index
   @autors = Autor.all.select(:id, :nombre, :apellido)
    render json: @autors
  end

  # GET /autors/1
  # GET /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors
  # POST /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to @autor, notice: 'Autor was successfully created.' }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1
  # PATCH/PUT /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to @autor, notice: 'Autor was successfully updated.' }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1
  # DELETE /autors/1.json
  def destroy
    @autor.destroy
    respond_to do |format|
      format.html { redirect_to autors_url, notice: 'Autor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autor_params
      params.require(:autor).permit(:nombre, :apellido)
    end
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/views/autors/_form.html.erb
<%= form_with(model: autor, local: true) do |form| %>
  <% if autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
      <% autor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1>Editing Autor</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Show', @autor %> |
<%= link_to 'Back', autors_path %>

app/views/autors/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
Usuario: <strong><%= current_user.email %></strong>.
<%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<%end %>

<h1>Lista de Autores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>


    <% @autors.each do |autor| %>
      <tr>
        <td><%= autor.nombre %></td>
        <td><%= autor.apellido %></td>
        <td><%= link_to 'Show', autor %></td>
        <td><%= link_to 'Edit', edit_autor_path(autor) %></td>
        <td><%= link_to 'Destroy', autor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Autor', new_autor_path %>

app/views/autors/new.html.erb
<h1>New Autor</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Back', autors_path %>

app/views/autors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @autor.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @autor.apellido %>
</p>

<%= link_to 'Edit', edit_autor_path(@autor) %> |
<%= link_to 'Back', autors_path %>